name: clube_ldv
description: Clube de descontos do Lugares do Vale
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flex_color_scheme: ^7.0.5
  google_fonts: ^4.0.4
  go_router: ^7.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/images/logo.jpeg"
    background_color: "#ffffff"
    theme_color: "#ffffff"