name: clube_ldv
description: Clube de descontos do Lugares do Vale
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flex_color_scheme: ^7.0.5
  google_fonts: ^4.0.4
  cached_network_image: ^3.2.3
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  auto_route: ^7.2.0
  freezed_annotation: ^2.2.0
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1
  logger: ^1.3.0
  mockito: ^5.4.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.3.3
  freezed: ^2.3.4
  custom_lint: ^0.4.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  auto_route_generator: ^7.1.1
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.2

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/images/logo.jpeg"
    background_color: "#ffffff"
    theme_color: "#ffffff"