name: Buidl and Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get Flutter Version
        run: flutter --version
      - name: Get Packages
        run: flutter pub get
      - name: Build Web for Release
        run: flutter build web --release
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLUBELDV_7684B }}'
          channelId: live
          projectId: clubeldv-7684b
